services:
  db:
    image: postgres:16-alpine
    container_name: race-team-planner-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: race-team-planner
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: race-team-planner-app
    profiles:
      - app
    depends_on:
      - db
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/race_team_planner
      - NEXTAUTH_SECRET=supersecret
      - NEXTAUTH_URL=http://localhost:3000
      - AUTH_TRUST_HOST=true

  jaeger:
    image: jaegertracing/jaeger:latest
    restart: always
    ports:
      - '16686:16686'

  prometheus:
    image: prom/prometheus:latest
    restart: always
    ports:
      - '9090:9090'
    volumes:
      - './prometheus-config.yaml:/etc/prometheus/prometheus.yml:Z'

  otel-col:
    image: otel/opentelemetry-collector
    ports:
      - '4317:4317'
      - '4318:4318'
    volumes:
      - './otel-collector-config.yaml:/etc/otelcol/config.yaml:Z'

volumes:
  db-data:
